### PR TITLE
Fixed implode(): Passing glue string after array is deprecated warning

### PR DESCRIPTION
**Pull request by btidude**

### CODE REVIEW

**Comment by Livijn** [comment]
@sahil-cb Can we merge this pr please? 😊

**Comment by thinker-amir** [comment]
please merge this.

**Comment by Fossil01** [comment]
Can this be tagged in a new version?

**Comment by oa-coinbase** [comment]
@Fossil01 done. Tagged as [release 1.0.11](https://github.com/coinbase/coinbase-commerce-php/releases/tag/1.0.11)

**Comment by Fossil01** [comment]
@oa-coinbase Thanks, but the package is not updated on Packagist yet. Seems auto update is also turned off:

https://packagist.org/packages/coinbase/coinbase-commerce

**Pull request merged**
