### PR TITLE
Modernize dependencies

### PR DESCRIPTION
**Pull request by ghost**
Allowed the use of Guzzle 7 and updated PHPUnit to a modern version. PHPUnit looked ok. But someone needs to test this.

### CODE REVIEW

**Comment by Fossil01** [comment]
@oa-coinbase

**Comment by Morinohtar** [comment]
Yeah, please add this.

**Comment by Morinohtar** [comment]
@oa-coinbase can you guys please review this PR and merge it? Tks

**Comment by Fossil01** [comment]
I have e-mailed them about it, got a reply they were looking into it. This was 3 weeks ago...

**Comment by Morinohtar** [comment]
You gotta an answer from them, not bad :)

**Review by puzka2 — APPROVED** [review]

**Comment by neoocm** [comment]
This was approved by puzka2... so what happened? why is it not yet in coinbase:master?

**Comment by Fossil01** [comment]
Pinging @oa-coinbase

**Comment by Morinohtar** [comment]
Pinging also @oa-coinbase ... this is really ridiculous.

**Comment by ImJustToNy** [comment]
+1

**Comment by Morinohtar** [comment]
@puzka2 can you merge or just approve? This is ridiculous...

**Comment by boriitoo** [comment]
Pinging @oa-coinbase @guacamoli @sahil-cb @vipulvpatil-cb

**Comment by Morinohtar** [comment]
@Fossil01 you are persistent, i admire you by that! But i dont think you will be that lucky lol

**Comment by ghost** [comment]
Ah. Latest commits werent supposed to be in this PR 😬

**Pull request closed without merging**
