### PR TITLE
Add PHP 8.0/8.1 compatibility

### LINKED ISSUE #41: Fatal error: Declaration of CoinbaseCommerce\Resources\ApiResource::asort()
How do i fix the error shown below
Fatal error: Declaration of CoinbaseCommerce\Resources\ApiResource::asort() must be compatible with ArrayObject::asort(int $flags = SORT_REGULAR)

### PR DESCRIPTION
**Pull request by IceQ1337**
See https://github.com/coinbase/coinbase-commerce-php/pull/42
Resolves #41

@ljharb I was not expecting to get any updates on this, but here is a new PR
Can you please also take a look at https://github.com/coinbase/coinbase-commerce-php/pull/34/ ?

### CODE REVIEW

**Comment by popoplanter** [comment]
i needed the original issue merged... so i wrote ljharb on twitter, which is probably why he commented on the original pull request. He isnt working on this project but forwarded the issue internally. But it does not seem like anyone is actively resolving anything here still @IceQ1337

**Comment by IceQ1337** [comment]
Yes. Unfortunately that seems to be the case. However, I received an email that said:
> Coinbase Commerce has increased the development pace for new features and capabilities

This may indicate that the API will be better maintained in the future, as it will likely need to be updated anyway.

**Comment by FlareCO** [comment]
It's 12/18/2021 still no merge.

**Comment by jxxe** [comment]
> PHP version 5.4 and above are supported.

This package is currently incompatible with PHP 8. Could an author please merge this 6-month old PR? I'd really rather not have to use a fork, though it doesn't seem like there will be many changes in the meantime.

**Comment by EHBradford** [comment]
In case someone line myself needs to a quick fix and cannot wait for the PR I was able to get this to work by modify the src/Resources/ApiResource.php file to have this:


 ```
   public function asort($flags = SORT_REGULAR)
    {
    asort($this->attributes, $flags);
    }

    public function ksort($flags = SORT_REGULAR)
    {
        ksort($this->attributes, $flags );
    }

```

I am not terribly familiar with GitHub protocol on submitting work-arounds, I hope this does not violate any rules.

**Comment by airidasbeno** [comment]
any update on this PR? 😄 we need support for php 8 😞

**Comment by IceQ1337** [comment]
> any update on this PR? 😄 we need support for php 8 😞

Although this PR restores basic compatibility with PHP 8.X, the library requires multiple changes in other places. Even if someone takes care of this PR and maybe even makes a few adjustments, it's only a matter of time before the library is out of date again.

You can use my fork instead. It is actively maintained and PRs are also gladly accepted.

https://github.com/IceQ1337/coinbase-commerce-php

**Pull request closed without merging**
